### ISSUE TITLE
hey having trouble trying to understand

### ISSUE THREAD

**Issue by hdhdhfhfirjf** [ItsBranK/UE3SDKGenerator#1]
I'm quite new to the whole usage of SDKs and im trying to play with it, I am trying to generate the SDK for the newest update of RL 3 days ago and im trying to compile your internal generator and im getting 2 errors that i don't understand, tried googling and i couldn't find a fix, correct if im wrong this generates a .dll that you inject into the game and it generates whats needed to get the SDK, am i going about this the wrong way?

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol main referenced in function "int __cdecl invoke_main(void)" (?invoke_main@@YAHXZ)	UE3SDKGenerator	C:\Users\admin\Desktop\UE3SDKGenerator-main\MSVCRTD.lib(exe_main.obj)	1	

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1120	1 unresolved externals	UE3SDKGenerator	C:\Users\admin\Desktop\UE3SDKGenerator-main\x64\Debug\UE3SDKGenerator.exe	1

**Comment by ItsBranK** [comment]
`C:\Users\admin\Desktop\UE3SDKGenerator-main\x64\Debug\UE3SDKGenerator.exe 1`

You're compiling as an exe, change it to dll in visual studio.

**Comment by hdhdhfhfirjf** [comment]
alright, i got that fixed but when i inject the DLL through both manual map and load library nothing generates, am i doing something wrong at this point?

**Comment by ItsBranK** [comment]
Prob, I use LoadLibraryA and it werks fine.

**Comment by hdhdhfhfirjf** [comment]
I tried LoadLibraryA and it doesn't output anything upon injection, is it something to do with the warnings on building the .dll ? does it output to a specific path?

**Comment by hdhdhfhfirjf** [comment]
Could you add me on discord so it's easier for me to get a response, im sure its tedious for you to have to come back and check here as well 
.e#5463

**Comment by ItsBranK** [comment]
I went ahead and recorded a video tutorial on how to use it and configure the generated dll, watch it here:

https://www.youtube.com/watch?v=e2igcsT-Yc8

**Comment by Artikus8** [comment]
upss the video is not available I'd really like to see this and I need it incredibly
