### ISSUE TITLE
Generator misses offsets

### ISSUE THREAD

**Issue by matix2** [ItsBranK/UE3SDKGenerator#10]
I have successfully generated an sdk, but on most classes this happens:

```cpp
uint8_t           TickGroup;        // 0x00D5 (0x0001) [0x0000000000000002] (CPF_Const)
class AActor*       Owner;        // 0x00D8 (0x0008) [0x0000000000000022] (CPF_Const | CPF_Net)
```

If tickgroup ends in offset D6,  there should be a padding of 0x2 before owner... Is there any way to automate this instead of fixing all classes by hand?

**Comment by ItsBranK** [comment]
It's your job to determine what kind of padding/alignment your game is using and configure it properly in Configuration.cpp. Looks like you're using AActor for for that offset and testing myself using a forced class padding 4 bytes those offsets are correct. I suggest you look into more how compilers do memory alignment and padding for classes/structs.

![image](https://user-images.githubusercontent.com/23649425/144537668-4d748587-f5e1-474e-9084-092dcaade2f3.png)

**Comment by ItsBranK** [comment]
The offset comments printed are from the direct value from `UProperty->Offset` in your games memory, taking your compilers settings out of the question and only using the ones determined by the game/unreal engine. That's partly the reason there's a "FinalAlignment" option in Configuration.cpp if a custom one is needed, this determines the pack pragma of your final generated sdk.

**Comment by matix2** [comment]
Thanks for the quick response, as you said, the game was using a different alignment from the one I specified in configuration.cpp, I changed it and now the sdk works perfectly :)
