### ISSUE TITLE
Std:filesystem::path ???

### ISSUE THREAD

**Issue by Youssef-Mekkaoui** [ItsBranK/UE3SDKGenerator#11]
Hello,

I'm having trouble with the ProcessPackages function you made.

![image](https://user-images.githubusercontent.com/16267835/148823831-7a4a4933-188d-4b60-bd0d-3db6bf91e522.png)

It cannot be recognize because std::filesystem::path cannot be found.

I do have filesystem and fstream in my includes.

Any idea ?

**Comment by ItsBranK** [comment]
Sounds like someone is using C++11 and not C++17
