### ISSUE TITLE
How to Reclass GNames ? (it seems not working)

### ISSUE THREAD

**Issue by Youssef-Mekkaoui** [ItsBranK/UE3SDKGenerator#12]
Hello Brank,

I'm trying to generate a unreal engine 3 SDK for rocket league but i have a problem, while trying to reverse gname to get the class structure informations.

https://imgur.com/a/bfwYPUd

I managed to get ArrayCount & ArrayMax.

but as soon as i set ArrayData to PTR, i can't open it and then i'm stuck ..

anyone could help please ?

Thanks.

**Comment by ItsBranK** [comment]
Boi this is not tech support for how to use reclass or reverse games.
