### ISSUE TITLE
about configuration.cpp / GameDefines.cpp 

### ISSUE THREAD

**Issue by Artikus8** [ItsBranK/UE3SDKGenerator#3]
It'll be a bit of a strange question and I'm a little embarrassed 
When editing configuration.cpp/gamedefines.cpp

How do we determine the "null" values? 
or  
How do we have to adjust according to the game? 

I don't want to damage your github account so I can't get them directly from you(iguees)
I would like to take advantage if there is a tutorial video 
The game I experiment with is RL

(I've been playing this game for 2 weeks and haven't seen any progress until I noticed you I think I will achieve this Everyone who starts will have trouble here, I'm a **light** for them xd i need sdk for your other project with this game)
![Screenshot_2](https://user-images.githubusercontent.com/46781129/119597155-2c1c1680-bde9-11eb-8290-460c2b41a590.png)

**Comment by ItsBranK** [comment]
You have to reverse the games classes by hand in ReClass, every game will be different and there is no way to automate the process. Same goes for globals, you have to find them yourself in IDA. This project just generates an sdk with the values you provide. Feckless has a tutorial for reversing classes, although a bit outdated it still applies to the current version of RL.

https://www.youtube.com/watch?v=yNe4jz1v0R4

**Comment by Artikus8** [comment]
I understand thanks. Can we talk about this very briefly on discord? I have been dealing with the game for a long time and the sdk part is blocking me a lot. I know your time is limited I don't want to waste our time but I believe I am a good student xD 
discord: Artikus#1506

**Comment by Artikus8** [comment]
okay I got my answer.Thanks for all your help, you are a very successful and good person. 
I hope you will be more successful !! <3
