### ISSUE TITLE
267 error in your code

### ISSUE THREAD

**Issue by ninosniper** [ItsBranK/UE3SDKGenerator#4]
i tried all configurations
always 267 error in your code when try to built
tried all possible configurations, still giving 267 errors while compiling !!!

**Comment by Artikus8** [comment]
Hey, you can add a screenshot of error. I can try to help you.

**Comment by ItsBranK** [comment]
By the sounds of it you didn't fill out anything in the GameDefines/PiecesOfCode files, this repository is not a place for help regarding how Unreal Engine 3 works.
